// client/project/src/components/ReviewsList.tsx
import { Link } from "react-router-dom";
import { IReview } from "../domain/IReview";
import { getUserId } from "../helpers/IdentityHelpers";
import { convertUtcToLocal, getFullDateTime } from "../helpers/TimeHelpers";
import { JwtContext } from "../routes/Root";
import { useContext, useEffect, useState } from "react";
import { ReviewService } from "../services/ReviewService";
import ReviewReaction from "./ReviewReaction";
import { IJWTResponse } from "../dto/IJWTResponse";
import ReviewStars from "./ReviewStars";


const reviewService = new ReviewService();

const ReviewsList = (props: {
    airportIata: string | undefined,
    selectedCategoryId: string,
    setErrors: (errors: string[]) => void,
    page: number,
    setPage: React.Dispatch<React.SetStateAction<number>>
}) => {
    
    const { jwtResponse, setJwtResponse } = useContext(JwtContext);
    const [reviews, setReviews] = useState([] as IReview[]);
    const [totalPages, setTotalPages] = useState(1);
    reviewService.initJwtResponse(jwtResponse, setJwtResponse);
    

    useEffect(() => {
        let isCancelled = false;
        const fetchReviews = async () => {
            if (props.selectedCategoryId === "") return;

            if (!props.airportIata || props.airportIata.length !== 3) {
                props.setErrors(["Inavlid url!"]);
                return;
            }

            const fetchedReviews = await reviewService.getAll(props.airportIata, props.selectedCategoryId, props.page);
            if (fetchedReviews && !isCancelled) {
                if (props.page === 1) {
                    setReviews(fetchedReviews.data);
                    setTotalPages(fetchedReviews.totalPageCount);
                } else {
                    setReviews(fetchedReviews.data);
                }
            } else if (!isCancelled) {
                props.setErrors(["Failed to load reviews!"]);
            }
        };
        fetchReviews();
        return () => {
            isCancelled = true;
        }
    }, [props])

    return (
        <>
        {jwtResponse && <Link to="edit">Add review</Link>}
        {props.page > 1 && 
            <button className="btn btn-primary" onClick={() => props.setPage((p) => p - 1)}>Previous page</button>}
        {reviews
            .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
            .map((review) => {
                return <ReviewBox review={review} jwtResponse={jwtResponse} key={review.id} />
        })}
        {props.page < totalPages && 
            <button className="btn btn-primary" onClick={() => props.setPage((p) => p + 1)}>Next page</button>}
        </>
    );
}

const ReviewBox = (props: { review: IReview, jwtResponse: IJWTResponse | null }) => {
    return (
        <div className="review-box">
            <ReviewStars rating={props.review.rating} setRating={undefined} />
            <p>{props.review.text}</p>
            <div className="text-right">{props.review.authorName} at {getFullDateTime(convertUtcToLocal(props.review.createdAt))}</div>
            <ReviewReaction  review={props.review} />

            {props.jwtResponse && getUserId(props.jwtResponse) === props.review.authorId &&
                <div className="text-right"><Link to={`edit/${props.review.id}`}>Edit</Link></div>
            }

        </div>
    );
}

export default ReviewsList;

// client/project-vue/src/components/ReviewsList.vue
<script setup lang="ts">
import type { IReview } from '@/domain/IReview';
import { ReviewService } from '@/services/ReviewService';
import { useJwtStore } from '@/stores/jwt';
import { ref, watchEffect } from 'vue';
import ReviewStars from './ReviewStars.vue';
import { getFullDateTime, convertUtcToLocal } from '@/helpers/TimeHelpers';
import { getUserId } from '@/helpers/IdentityHelpers';
import ReviewReaction from './ReviewReaction.vue';

const props = defineProps<{
    airportIata: string,
    selectedCategoryId: string,
    setSelectedCategoryId: (id: string) => void
    page: number,
    setPage: (page: number) => void
}>()


const reviewService = new ReviewService();
const jwtStore = useJwtStore();
reviewService.initJwtResponse(jwtStore.jwtResponse, jwtStore.setJwtResponse);

const totalPages = ref(1);
const reviews = ref(undefined as IReview[] | undefined);

const fetchReviews = async () => {
    if (props.selectedCategoryId === "") return;

    if (!props.airportIata || props.airportIata.length !== 3) {
        return;
    }

    const fetchedReviews = await reviewService.getAll(props.airportIata, props.selectedCategoryId, props.page);
    if (fetchedReviews) {
        if (props.page === 1) {
            totalPages.value = fetchedReviews.totalPageCount;
        }
        reviews.value = fetchedReviews.data
            .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
    }
};

watchEffect(() => {
    fetchReviews();
});



</script>

<template>
    <RouterLink :to="'reviews/edit'" v-if="jwtStore.jwtResponse">Add review</RouterLink>
    <button v-if="props.page > 1" 
        class="btn btn-primary" @click="() => props.setPage(props.page-1)">Previous page</button>

    <div class="review-box" v-for="review in reviews" :key="review.id!">
        <ReviewStars :rating="review.rating" />
        <p>{{review.text}}</p>
        <div class="text-right">
            {{review.authorName}} at {{getFullDateTime(convertUtcToLocal(review.createdAt))}}</div>
        <ReviewReaction :review="review" />

        <div v-if="jwtStore.jwtResponse && getUserId(jwtStore.jwtResponse) === review.authorId" 
            class="text-right">
            <RouterLink :to="`reviews/edit/${review.id}`">Edit</RouterLink>
        </div>

    </div>
    <button v-if="props.page < totalPages" 
        class="btn btn-primary" @click="() => props.setPage(props.page - 1)">Next page</button>
</template>
