// client/project/src/components/ReviewStars.tsx
const ReviewStars = (props: { rating: number, setRating: undefined | React.Dispatch<React.SetStateAction<number>> }) => {
    
    const handleClick = (i: number): void => {
        if (props.setRating) {
            props.setRating(i);
        }
    }
    
    return (
        <div>            {
            Array.from(Array(5).keys()).map(i => {
                i = i + 1;
                return ( 
                    <span key={i} 
                        className={"fa fa-star" + (props.rating >= i ? " checked" : "") + (props.setRating ? " user-rating" : "")}
                        onClick={() => {handleClick(i)}} >
                    </span>
                )
            })}
        </div>
    );
}

export default ReviewStars;

// client/project-vue/src/components/ReviewStars.vue
<script setup lang="ts">
const props = defineProps<{
    rating: number,
    setRating?: (rating: number) => void
}>() 


const handleClick = (i: number): void => {
    if (props.setRating) {
        props.setRating(i);
    }
}
</script>

<template>
    <div>
        <span v-for=" i in [1, 2, 3, 4, 5]" :key="i"
            :class="'fa fa-star' + (props.rating >= i ? ' checked' : '') + (props.setRating ? ' user-rating' : '')"
            @click="() => {handleClick(i)}" >
        </span>
    </div>
</template>

<style scoped>
.fa-star.checked {
    color: orange;
}
.fa-star.user-rating{
    cursor: pointer;
}
</style>
