// client/project/src/components/ValidationErrors.tsx
const ValidationErrors = (props: {validationErrors: string[]}) => {
    if (props.validationErrors.length === 0) {
        return <></>;
    }
    else {
        return (
            <ul className="text-danger">
              {
                props.validationErrors.map((error) =>
                  <li key={error}>
                    {error}
                  </li>
              )}
            </ul>
        );
    }
}

export default ValidationErrors;

// client/project-vue/src/components/ValidationErrors.vue
<script setup lang="ts">
defineProps<{
    validationErrors: string[]
}>()
</script>


<template>
    <ul v-if="validationErrors.length > 0">
        <li v-for="error in validationErrors" :key="error">
            {{ error }}
        </li>
    </ul>
</template>

<style scoped>
    ul {
        color: red;
    }
</style>
