// client/project/src/components/IdentityHeader.tsx
import { useContext } from "react";
import { Link, useNavigate } from "react-router-dom";
import { JwtContext } from "../routes/Root";
import { IdentityService } from "../services/IdentityService";
import { getUserName } from "../helpers/IdentityHelpers";


const identityService = new IdentityService();

const IdentityHeader = () => {
    const { jwtResponse, setJwtResponse } = useContext(JwtContext);
    const navigate = useNavigate();

    const logout = () => {
        if (jwtResponse)
            identityService.logout(jwtResponse).then(response => {
                if (setJwtResponse)
                    setJwtResponse(null);
                navigate("/");
            });
    }
    
    if (jwtResponse) {
        return (
            <>
                <li className="nav-item">
                    <Link to="info" className="nav-link text-dark">
                        {getUserName(jwtResponse)}
                    </Link>
                </li>
                <li className="nav-item">
                    <button onClick={(e) => {
                        e.preventDefault();
                        logout();
                    }} className="fake-button nav-link text-dark">Logout</button>
                </li>
            </>
        );
    }
    return (
        <>
            <li className="nav-item">
                <Link to="register" className="nav-link text-dark">Register</Link>
            </li>
            <li className="nav-item">
                <Link to="login" className="nav-link text-dark">Login</Link>
            </li>
        </>
    );
}

export default IdentityHeader;

// client/project-vue/src/components/identity/IdentityHeader.vue
<script setup lang="ts">
import { useJwtStore } from '@/stores/jwt';
import { getUserName } from '@/helpers/IdentityHelpers';
import { IdentityService } from '@/services/IdentityService';
import router from '@/router';

const jwtStore = useJwtStore();

const identityService = new IdentityService();

const logout = (e: any) => {
    e.preventDefault();
    if (jwtStore.jwtResponse)
        identityService.logout(jwtStore.jwtResponse).then((response) => {
            if (response) {
                jwtStore.jwtResponse = null;
                router.push("/");
            }
    });
}

</script>

<template>
    <template v-if="jwtStore.jwtResponse">
        <li class="nav-item">
            <span class="nav-link text-dark">
                {{ getUserName(jwtStore.jwtResponse) ?? "" }}
            </span>
        </li>
        <li class="nav-item">
            <button @click="(e) => logout(e)" class="fake-button nav-link text-dark">Logout</button>
        </li>
    </template>

    <template v-else>
        <li class="nav-item">
            <RouterLink :to="'/register'" class="nav-link text-dark">Register</RouterLink>
        </li>
        <li class="nav-item">
            <RouterLink :to="'/login'" class="nav-link text-dark">Login</RouterLink>
        </li>
    </template>
</template>
